$From = "yarish@gmail.com"
$To = "yjanakiraman@deloitte.com"
$Cc = "yjanakiraman@deloitte.com"
$Attachment = "{{ destination }}/{{task_name}}.log"
$Subject = "Ansible task - windows security update completed"
$Body = "body generated by powershell"
$SMTPServer = "smtp.gmail.com"
$SMTPPort = "587"

$Username = $From
$Password = Get-Content "{{destination}}/password.txt" | ConvertTo-SecureString 
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $Username, $Password

Send-MailMessage -From $From -to $To -Cc $Cc -Subject $Subject `
-Body $Body -SmtpServer $SMTPServer -port $SMTPPort -UseSsl `
-Credential $Credential -Attachments $Attachment
